// Generated by gencpp from file xf_mic_asr_offline/VoiceCmdRequest.msg
// DO NOT EDIT!


#ifndef XF_MIC_ASR_OFFLINE_MESSAGE_VOICECMDREQUEST_H
#define XF_MIC_ASR_OFFLINE_MESSAGE_VOICECMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xf_mic_asr_offline
{
template <class ContainerAllocator>
struct VoiceCmdRequest_
{
  typedef VoiceCmdRequest_<ContainerAllocator> Type;

  VoiceCmdRequest_()
    : voice_cmd()  {
    }
  VoiceCmdRequest_(const ContainerAllocator& _alloc)
    : voice_cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _voice_cmd_type;
  _voice_cmd_type voice_cmd;





  typedef boost::shared_ptr< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VoiceCmdRequest_

typedef ::xf_mic_asr_offline::VoiceCmdRequest_<std::allocator<void> > VoiceCmdRequest;

typedef boost::shared_ptr< ::xf_mic_asr_offline::VoiceCmdRequest > VoiceCmdRequestPtr;
typedef boost::shared_ptr< ::xf_mic_asr_offline::VoiceCmdRequest const> VoiceCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator1> & lhs, const ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.voice_cmd == rhs.voice_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator1> & lhs, const ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xf_mic_asr_offline

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7806d69c897ffd9ad7c1697602fec40";
  }

  static const char* value(const ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7806d69c897ffd9ULL;
  static const uint64_t static_value2 = 0xad7c1697602fec40ULL;
};

template<class ContainerAllocator>
struct DataType< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xf_mic_asr_offline/VoiceCmdRequest";
  }

  static const char* value(const ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求部分 - 指定语音指令\n"
"string voice_cmd\n"
;
  }

  static const char* value(const ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voice_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VoiceCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xf_mic_asr_offline::VoiceCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "voice_cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.voice_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XF_MIC_ASR_OFFLINE_MESSAGE_VOICECMDREQUEST_H
