// Generated by gencpp from file xf_mic_asr_offline/VoiceCmd.msg
// DO NOT EDIT!


#ifndef XF_MIC_ASR_OFFLINE_MESSAGE_VOICECMD_H
#define XF_MIC_ASR_OFFLINE_MESSAGE_VOICECMD_H

#include <ros/service_traits.h>


#include <xf_mic_asr_offline/VoiceCmdRequest.h>
#include <xf_mic_asr_offline/VoiceCmdResponse.h>


namespace xf_mic_asr_offline
{

struct VoiceCmd
{

typedef VoiceCmdRequest Request;
typedef VoiceCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VoiceCmd
} // namespace xf_mic_asr_offline


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xf_mic_asr_offline::VoiceCmd > {
  static const char* value()
  {
    return "db201c99548e0ca4c062a24b1bddb118";
  }

  static const char* value(const ::xf_mic_asr_offline::VoiceCmd&) { return value(); }
};

template<>
struct DataType< ::xf_mic_asr_offline::VoiceCmd > {
  static const char* value()
  {
    return "xf_mic_asr_offline/VoiceCmd";
  }

  static const char* value(const ::xf_mic_asr_offline::VoiceCmd&) { return value(); }
};


// service_traits::MD5Sum< ::xf_mic_asr_offline::VoiceCmdRequest> should match
// service_traits::MD5Sum< ::xf_mic_asr_offline::VoiceCmd >
template<>
struct MD5Sum< ::xf_mic_asr_offline::VoiceCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::VoiceCmd >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::VoiceCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::VoiceCmdRequest> should match
// service_traits::DataType< ::xf_mic_asr_offline::VoiceCmd >
template<>
struct DataType< ::xf_mic_asr_offline::VoiceCmdRequest>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::VoiceCmd >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::VoiceCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xf_mic_asr_offline::VoiceCmdResponse> should match
// service_traits::MD5Sum< ::xf_mic_asr_offline::VoiceCmd >
template<>
struct MD5Sum< ::xf_mic_asr_offline::VoiceCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::VoiceCmd >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::VoiceCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::VoiceCmdResponse> should match
// service_traits::DataType< ::xf_mic_asr_offline::VoiceCmd >
template<>
struct DataType< ::xf_mic_asr_offline::VoiceCmdResponse>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::VoiceCmd >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::VoiceCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XF_MIC_ASR_OFFLINE_MESSAGE_VOICECMD_H
