# Description:
# 代价地图通用参数配置文件,就是全局代价地图和局部代价地图
# 共同都需要配置的参数,各参数意义如下:

# 该版本修改了机器人足迹 footprint 的范围


# ———————————————————————————————————————————修改这里————————————————————————————————————————
footprint: [[0.17, -0.125], [0.17, 0.125], [-0.17, 0.125], [-0.17, -0.125]]

obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true 
  obstacle_range: 2.0
  raytrace_range: 2.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: laser_frame,
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true,
    inf_is_valid: true 
  }

inflation_layer:
  enabled: true
  cost_scaling_factor: 25.0
# inflation_radius: 0.2
  inflation_radius: 0.25
#0.15

static_layer: # 这个层通常只在全局代价地图中启用，但写在这里作为通用配置也没问题
  enabled: true # 在全局地图中通常为 true，在局部地图中通常为 false (通过 plugins 控制)